### ISSUE TITLE
panic: index out of bounds

### ISSUE THREAD

**Issue by OHNONOTAMOTH** [MikhailKravets/NeuroFlow#6]
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /home/moth/.cargo/registry/src/github.com-1ecc6299db9ec823/neuroflow-0.1.3/src/lib.rs:356:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:85:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:189:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/vec/mod.rs:2531:9
   6: neuroflow::FeedForward::backward
             at /home/moth/.cargo/registry/src/github.com-1ecc6299db9ec823/neuroflow-0.1.3/src/lib.rs:356:48
   7: neuroflow::FeedForward::fit
             at /home/moth/.cargo/registry/src/github.com-1ecc6299db9ec823/neuroflow-0.1.3/src/lib.rs:463:9
   8: neuroflow::FeedForward::train
             at /home/moth/.cargo/registry/src/github.com-1ecc6299db9ec823/neuroflow-0.1.3/src/lib.rs:439:13
   9: neuralnetrust::main
             at ./src/main.rs:41:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
The terminal process "cargo 'run', '--package', 'neuralnetrust', '--bin', 'neuralnetrust'" terminated with exit code: 101.
```

when using the lib, I get this error

**Comment by andrei-lus** [comment]
Show the code

**Comment by MikhailKravets** [comment]
Should be fixed in #8. Please, feel free to re-open the issue if the error remains
